# Generated by Django 3.1.6 on 2021-02-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='files',
            field=models.FileField(default=None, upload_to='files/medias'),
        ),
    ]
