# Generated by Django 3.1.6 on 2021-02-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210219_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='files',
            field=models.FileField(upload_to='files/media/'),
        ),
    ]
