# Generated by Django 3.1.6 on 2021-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210219_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='files/images'),
        ),
    ]
