# Generated by Django 3.1.6 on 2021-02-21 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_posts_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
    ]
